### ISSUE TITLE
[question] runtime_createExternalSignerPayload

### ISSUE THREAD

**Issue by roccomuso** [polkascan/substrate-interface#1]
I saw this lib provide a `runtime_createExternalSignerPayload` method.
I'm looking for easy way to create an extrinsic transaction without having to "download" client-side the whole metadata.

Could you help me understand if that method is usable and what this repo is used for?

**Comment by arjanz** [comment]
Hi Rocco, methods like `runtime_createExternalSignerPayload` and in general `runtime_*` are convenience methods we added in our project https://github.com/polkascan/substrate-interface-api, which can be placed as a proxy in front of a node endpoint.

Basically if you use our substrate-interface as a service, you don't need to do any decoding of the data yourself. Have a look at the docker-compose files https://github.com/polkascan/substrate-interface to have an idea how to run this 

And after running, you can point your client to the new exposed endpoint, for example http://127.0.0.1:8000 (in stead of http://127.0.0.1:9933) if you use the supplied docker-compose https://github.com/polkascan/substrate-interface/blob/master/docker-compose.polkadot-public.yml

An example GUI is also supplied at http://127.0.0.1:8001

Then you will have the additional runtime_* endpoints which will supply decoded storage calls, extrinsics, etc

**Comment by arjanz** [comment]
After you have the endpoint up and running, you can use the following POST to retrieve a balance:

```bash
curl -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"runtime_getState","params":["System","Account",["EMofbvvJRnTxmrLGMXHoebXnxTWqmpQZipLd7QhHzJdLbdd"],null],"id":4}' http://127.0.0.1:8000/
```
Which will result in:

```json
{"jsonrpc": "2.0", "result": {"nonce": 2, "refcount": 0, "data": {"free": 29348000000, "reserved": 0, "miscFrozen": 0, "feeFrozen": 0}}, "id": 4}
```

**Comment by roccomuso** [comment]
Is there also a call to get transactions list of a given address?

**Comment by arjanz** [comment]
Not directly from the node, this is not indexed. But you can retrieve it from the API of block explorers like Polkascan or Subscan. (e.g. https://explorer-31.polkascan.io/polkadot/api/v1/extrinsic?filter[address]=12NLgzqfhuJkc9mZ5XUTTG85N8yhhzfptwqF1xVhtK3ZX7f6&page[size]=25)

**Comment by roccomuso** [comment]
@arjanz I see. Is there any doc about that? like a cursor mechanism or a way to filter by date intervals?

**Comment by arjanz** [comment]
You can use the `page[size]=25` and `page[number]=x` parameters for paging the result, there is a hard cap on 100 items per page on top of my head
