### ISSUE TITLE
Cannot read property 'ss58Address' of undefined in create-extrinsic page

### ISSUE THREAD

**Issue by roccomuso** [polkascan/substrate-interface#2]
I tried to create a simple extrinsic from `http://127.0.0.1:8001/create-extrinsic` of type `balances.transfer`
And got that error on the js console:

![image](https://user-images.githubusercontent.com/6730217/95360319-818fcb80-08cb-11eb-99be-766493e4383c.png)

> ERROR TypeError: Cannot read property 'ss58Address' of undefined
    at t.requestSignaturePayload (main-es2015.850edbdc68db407ce1d4.js:1)
    at main-es2015.850edbdc68db407ce1d4.js:1
    at Jo (main-es2015.850edbdc68db407ce1d4.js:1)
    at i (main-es2015.850edbdc68db407ce1d4.js:1)
    at HTMLButtonElement.<anonymous> (main-es2015.850edbdc68db407ce1d4.js:1)
    at u.invokeTask (polyfills-es2015.6375159acce2670023c4.js:1)
    at Object.onInvokeTask (main-es2015.850edbdc68db407ce1d4.js:1)
    at u.invokeTask (polyfills-es2015.6375159acce2670023c4.js:1)

Is this because I didn't do any "scan address"?
I'm working on the polkadot network btw

**Comment by roccomuso** [comment]
```bash
curl --location --request POST 'http://localhost:8000' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "runtime_createExtrinsic",
    "params": [
    	"E8NhfVL6VE9a3Sb3TqRGw4n37vDSwdu83SxVtNzkunsPC51",
        "Balances",
    	"transfer", 
    	{
        	"dest": "E8NhfVL6VE9a3Sb3TqRGw4n37vDSwdu83SxVtNzkunsPC51",
        	"value": 1
    	}
    ],
    "id": 1
}'
```

Also this sample curl, bypassing the GUI gives back this error:

> {"error": {"code": -999, "message": "Not enough parameters provided"}, "id": 1}

**Comment by arjanz** [comment]
Yes, if you want to create and send an extrinsic on the provided GUI you need to scan an address with Parity Signer first. That said, the provided GUI is actually nothing more than an example application to showcase the underlying functionality provided with https://github.com/polkascan/substrate-interface-api and the library https://github.com/polkascan/py-substrate-interface which is the core of all the functionality. 

The GUI also make it possible to verify and generate keypairs for example, which will never be a valid usecase to send this over the network, but is just intended to showcase the library (https://github.com/polkascan/py-substrate-interface)
