### ISSUE TITLE
[question] is this fully compatible with kusama?

### ISSUE THREAD

**Issue by roccomuso** [polkascan/substrate-interface#4]
Both Kusama and Polkadot should use the same substrate api, I'm wondering if something changes under the hood or if the concepts are the same (with same extrinsic and so on). And if this substrate-interface api are also able to create and broadcast Kusama tokens.

Thanks!

**Comment by arjanz** [comment]
Certainly, both chains are based on 'Substrate' (https://substrate.dev) and our library is basically compatible with Substrate-based chains. The only difference is those chains (like Polkadot and Kusama) have a slightly different runtime ('firmware' so to say), so you have to tell our libraries how to deal with certain types which we call the 'type registry'. 

To make life easier we included a config file for Kusama as well which has all the variables set correctly already: https://github.com/polkascan/substrate-interface/blob/master/docker-compose.kusama-public.yml

**Comment by roccomuso** [comment]
thanks for the clear explanation! I will give it a try as well!
