### ISSUE TITLE
invalid literal for int() with base 10 for runtime_submitExtrinsic

### ISSUE THREAD

**Issue by gutenye** [polkascan/substrate-interface#5]
I tried this example from [doc](https://documenter.getpostman.com/view/9969999/SWT5iLXH#e417a4fb-e206-49b2-950d-c3deb77448fb)

```
curl --location --request POST 'http://localhost:8000' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "runtime_submitExtrinsic",
    "params": [
    	"E8NhfVL6VE9a3Sb3TqRGw4n37vDSwdu83SxVtNzkunsPC51",
        "Balances",
    	"transfer", 
    	{
        	"dest": "E8NhfVL6VE9a3Sb3TqRGw4n37vDSwdu83SxVtNzkunsPC51",
        	"value": 1
    	},
    	"0x2ede78e5d4bdd811909fb960517eb0e47d3d86d3c940e65e7bbdb8776f9869436d91e19493d4351a093f75b6987f436bd61f1e43de2599585f2bf22771c7f487"
    ],
    "id": 1
}'
```

Got an error with

```
{"error": {"code": -999, "message": "invalid literal for int() with base 10: '0x2ede78e5d4bdd811909fb960517eb0e47d3d86d3c940e65e7bbdb8776f9869436d91e19493d4351a093f75b6987f436bd61f1e43de2599585f2bf22771c7f487'"}, "id": 1}
```

Any idea what does it mean?

I'm using the latest master branch.

**Comment by gutenye** [comment]
I solved above, the doc is outdated, it's now with params [tip, era, cryptoType, signature].

But I now get `{"code":-999,"message":"Value must be the string '00' or tuple of two ints"}` one. The signature is invalid? Do you have an example on how to sign the signaturePayload?

**Comment by arjanz** [comment]
> I solved above, the doc is outdated, it's now with params [tip, era, cryptoType, signature].

Noted, I'll update the docs soon. Btw you can use the [example GUI](https://github.com/polkascan/substrate-interface-gui) and open up the console to give more context and see what exactly should be posted.

> But I now get `{"code":-999,"message":"Value must be the string '00' or tuple of two ints"}` one. The signature is invalid? Do you have an example on how to sign the signaturePayload?

You can use [Polkadot-JS apps](https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/signing) or [subkey](https://github.com/paritytech/substrate/tree/master/bin/utils/subkey) to sign the signature payload:

```bash
echo -n "05005e9126f218e28ab981811e25e345f6c3c314f7deceb62a3e738aaf3690add4610284d717450300000100000001000000c0cd96a7ee70debe9b0713ac343d8406ab81324076670ea8f3f9f510a0d9a4f0f5c179098d480a60bd452e0555cb5172dc6320898e06f4886d69b6149e1e276f" | subkey sign --hex "nature exchange gasp toy result bacon coin broccoli rule oyster believe lyrics"
```

**Comment by gutenye** [comment]
I'm using the example from [here](https://github.com/polkascan/substrate-interface-api/issues/1#issuecomment-705670095)

```
curl --location --request POST 'http://localhost:8000' \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "jsonrpc": "2.0",
        "method": "runtime_submitExtrinsic",
        "params": [
        "13Rfiutv3JGWJDntux2chFcR9RuoU4MWaEKgggrMdKfsRCU1",
            "Balances",
        "transfer",
        {
            "dest": "12nV9cr7Xr31ef3QTHmF3r4gVzAvjQZNBqi5Pk86NH7emyoN",
            "value": 100000000
        },
        0,
        0,
        0,
     "0x0058445b5b191645220b3a5251ecc0181b89395d5f50a6f1805798728b29267ef1327bf386f0cc74d7c6b533817a201278689afa60383a228efb38d3c615197d0d"
        ],
        "id": 1
    }'
```

Three 0s are for `tip`, `era`, and `crypto_type` (ed25519)

Still get

```
{"jsonrpc": "2.0", "error": {"code": -999, "message": "Value must be the string '00' or tuple of two ints"}, "id": 1}
```

As the tx is already in the blockchain, the signature is definitely wrong, it should return the "signature invalid" message, not above message.

**Comment by arjanz** [comment]
The `era` in your example is in the wrong format, it should be `null` for an immortal era (doesn't expire) or in `{"period": 256, "current": 2010000}` format (approx. 256 blocks after block number 2010000).

So example will be:

```bash
curl --location --request POST 'http://localhost:8000' \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "jsonrpc": "2.0",
        "method": "runtime_submitExtrinsic",
        "params": [
        "5HkD8qaiqysuAJdjxcPYGRqRzTDSC6W6Tfge9GaQ5VeazkMj",
            "Balances",
        "transfer",
        {
            "dest": "5HkD8qaiqysuAJdjxcPYGRqRzTDSC6W6Tfge9GaQ5VeazkMj",
            "value": 100000000
        },
        0,
        {"period": 256, "current": 2010000},
        0,
     "0x0058445b5b191645220b3a5251ecc0181b89395d5f50a6f1805798728b29267ef1327bf386f0cc74d7c6b533817a201278689afa60383a228efb38d3c615197d0d"
        ],
        "id": 1
    }'
```

**Comment by gutenye** [comment]
@arjanz Thank you very much, you are fast and helpful~
